ARG UBUNTU_VERSION="jammy"
FROM external-docker.artifactory.oxfordnanolabs.local/ubuntu:${UBUNTU_VERSION}

# need to repeat this for stupid reasons
ARG UBUNTU_VERSION="jammy"

ARG DEBIAN_FRONTEND=noninteractive

ARG ARROW_VERSION="18.0.0-1"
RUN apt-get update && \
    apt-get install -y -V ca-certificates wget && \
    wget https://apache.jfrog.io/artifactory/arrow/ubuntu/apache-arrow-apt-source-latest-${UBUNTU_VERSION}.deb && \
    apt-get install -y -V ./apache-arrow-apt-source-latest-${UBUNTU_VERSION}.deb && \
    apt-get update && \
    apt-get install -y cmake build-essential libzstd-dev libzstd-dev libflatbuffers-dev libarrow-dev=${ARROW_VERSION} && \
    rm -rf /var/lib/apt/lists/*
