set(MKR_VERSION_MAJOR 0)
set(MKR_VERSION_MINOR 0)
set(MKR_VERSION_REV 11)

set(MKR_NUMERIC_VERSION "${MKR_VERSION_MAJOR}.${MKR_VERSION_MINOR}.${MKR_VERSION_REV}")
set(MKR_FULL_VERSION "${MinKNOW_NUMERIC_VERSION}")
