set(POD5_VERSION_MAJOR 0)
set(POD5_VERSION_MINOR 0)
set(POD5_VERSION_REV 41)

set(POD5_NUMERIC_VERSION "${POD5_VERSION_MAJOR}.${POD5_VERSION_MINOR}.${POD5_VERSION_REV}")
set(POD5_FULL_VERSION "${POD5_NUMERIC_VERSION}")
